exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('tasks').truncate()
        .then(function() {
            // Inserts seed entries
            return knex('tasks').insert([
                { projects_id: 1, step_number: 1, taskDescription: 'collect vaccum, bucket and rags and find where i put the car cleaners crate', notes: 'all items should be in the north east corner of garage', taskCompleted: false },
                { projects_id: 1, step_number: 2, taskDescription: 'spray down console and let soak while vaccuming the seats and floorboards', notes: 'fold down seats too to get those hard to reach areas... kids are messy, you know...', taskCompleted: false },
                { projects_id: 1, step_number: 3, taskDescription: 'spray rag and wipe down all of dash and console areas. look for all the little spots that are easy to miss.. it counts', notes: 'there is alwasy a spare walmart sack in the trunk to put the trash found and throw away in one go.', taskCompleted: false },
                { projects_id: 1, step_number: 4, taskDescription: 'throw trash collected and put away cleaners and put any reusable rags into dirty shop laundry.. ', notes: 'do this weekly to keep car looking newer for longer... ', taskCompleted: false },
                { projects_id: 2, step_number: 1, taskDescription: 'collect what cleaners/cleaner you prefer.. 1 rag for kitchen counter and kitchen table and another for window trim and doors and ceiling fans', notes: 'separate what rags are for what you dont want to use a counter rag after wiping the ceiling fan blades. eeew!', taskCompleted: false },
                { projects_id: 2, step_number: 2, taskDescription: 'start with counters after you clear them of unnecessary items; start from wall/backsplash and work you way along backsplash then pull towards front of counter and off.(gonna vaccum so dont worry about what falls for now) then do kitchen table after re-wetting with another spray of cleaner(lightly rinse rag before and remove any counter debris; also dont over spray, some cleaners are rough on some surfaces so read your cleaner bottle for specifics)', notes: 'we are using a top down method', taskCompleted: false },
                { projects_id: 2, step_number: 3, taskDescription: 'once done toss counter/table rag into laundry and prep second rag for dusting ceiling fans then window trim and other flat surfaces throughout the home. (remember think top down)', notes: 'come on do you really need more notes for this part?', taskCompleted: false },
                { projects_id: 2, step_number: 4, taskDescription: 'throw dusting rag into laundry and plug in that vaccum and now vaccum all floors (its faster than sweeping). after you have vaccumed the entire house dump out the container holding all that nastiness! get rid of it... do not be gross about it.', notes: ' obviously put stuff away now that your done....lol. come on ', taskCompleted: false },
                { projects_id: 3, step_number: 1, taskDescription: 'collect screws, stud-finder, leveler, a extra pair of hands and a pencil and power drill along with the tv and mount', notes: 'most mounts come with screws of some kind and spacers.. look at your manual to be more specific.', taskCompleted: false },
                { projects_id: 3, step_number: 2, taskDescription: 'argue about where exactly to put tv with spouse... this is important..lol. then use stud finder to determine and mark with pencil where the studs(boards) are in the wall. ', notes: 'dont forget to argue about position specifics and whether the tv is too big or not', taskCompleted: false },
                { projects_id: 3, step_number: 3, taskDescription: 'now that the argument and where the boards are is out the way; have your spare hands hold the wall side of the mount in place. use the level to make sure you can convince your spouse that it is level and its realy just the ceiling wall that is not level. Next continue to have extra hands hold up wall side mount while you use the power drill to screw the wall side of mount to those in wall studs(boards). use mount kit screws to put tv side of mount onto tv per kit instructions', notes: 'i would say duh but you are reading this instructional', taskCompleted: false },
                { projects_id: 3, step_number: 4, taskDescription: 'Finally! have your extra pair of hands hellp you slide the tv(with tv side of mount attatched) onto the wall side of the mount which is now securely mounted with at least 4 screws into the studs(boards in wall). now plug all you tv junk in and enjoy your very slightly lopp sided tv....lol.(it is really just the wall)', notes: 'duh.... put your stuff up now that you are done. ENJOY', taskCompleted: false },
            ]);
        });
};